CREATE TABLE IF NOT EXISTS dairy (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_name TEXT NOT NULL,
  task_description TEXT NOT NULL DeFAULT '',
  craeted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  finish_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP

)
